environment:
  name: test
  project: cdf-bootcamp-08-test
  validation-type: test
  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee
variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      data_foundation:
        data_developer_source_id: 73f4038e-fe0d-4a48-9e49-6bba1a9b70be
      ice_cream_api:
        icapi_extractors_source_id: 055a012a-57b2-40cd-bcf0-3a741459e649
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: a91732ba-eee7-42bd-bcaa-43a68bc85bd3
        icapi_trigger_client_secret: uHS8Q~ORUlzpSY4eq91K5vP1Ta125Zvq7VKKgbxB
        icapi_extractors_client_id: a91732ba-eee7-42bd-bcaa-43a68bc85bd3
        icapi_extractors_client_secret: uHS8Q~ORUlzpSY4eq91K5vP1Ta125Zvq7VKKgbxB

      use_cases:
        oee:
          data_pipeline_oee_source_id: 994ddf6e-4afc-4b13-8fce-6200af57dde3
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: 6112415c-7389-4d63-b2ba-734609f084fc
          data_pipeline_oee_client_secret: UjH8Q~.OB6IxlnoaalpoXrhIe1pXUgOplw-6BbmI
